apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: bmi-service
  name: bmi-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: bmi-service
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.34.0 (HEAD)
      labels:
        io.kompose.service: bmi-service
    spec:
      containers:
        - env:
            - name: FLASK_APP
              value: bmi_service.py
          image: abanikaurkohli/bmi-service:latest
          name: bmi-service
          ports:
            - containerPort: 5002
              protocol: TCP
          volumeMounts:
            - mountPath: /app
              name: bmi-service-cm0
      restartPolicy: Always
      volumes:
        - configMap:
            name: bmi-service-cm0
          name: bmi-service-cm0
