apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: exercise-service
  name: exercise-service
spec:
  ports:
    - name: "5004"
      port: 5004
      targetPort: 5003
  selector:
    io.kompose.service: exercise-service
