apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: frontend
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.34.0 (HEAD)
      labels:
        io.kompose.service: frontend
    spec:
      containers:
        - env:
            - name: FLASK_APP
              value: streamlit_frontend.py
          image: abanikaurkohli/frontend:latest
          livenessProbe:
            exec:
              command:
                - curl
                - --silent
                - --fail
                - http://localhost:8501
            failureThreshold: 3
            initialDelaySeconds: 10
            periodSeconds: 30
            timeoutSeconds: 10
          name: frontend
          ports:
            - containerPort: 8501
              protocol: TCP
          volumeMounts:
            - mountPath: /app
              name: frontend-cm0
      restartPolicy: Always
      volumes:
        - configMap:
            name: frontend-cm0
          name: frontend-cm0
