apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: user-service
  name: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: user-service
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.34.0 (HEAD)
      labels:
        io.kompose.service: user-service
    spec:
      containers:
        - env:
            - name: FLASK_APP
              value: user_service.py
          image: abanikaurkohli/user-service:latest
          name: user-service
          ports:
            - containerPort: 5001
              protocol: TCP
          volumeMounts:
            - mountPath: /app
              name: user-service-cm0
      restartPolicy: Always
      volumes:
        - configMap:
            name: user-service-cm0
          name: user-service-cm0
