apiVersion: apps/v1
kind: Deployment
metadata:
  name: bmi-service
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bmi-service
  template:
    metadata:
      labels:
        app: bmi-service
    spec:
      containers:
        - name: bmi-service
          image: abanikaurkohli/bmi-service:latest
          ports:
            - containerPort: 5002
          livenessProbe:
            httpGet:
              path: /health
              port: 5002
            initialDelaySeconds: 60  # Increase delay further if needed
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /readiness
              port: 5002
            initialDelaySeconds: 60  # Increase delay further if needed
            periodSeconds: 15
          command:
            - "flask"
            - "run"
            - "--host=0.0.0.0"
            - "--port=5002"
            - "--app=/Users/I528654/Documents/BITS Mtech/Third Semester/Assignements/ScalableServiceAss2/health_prediction_service/bmi_service.py/bmi_service.py"
          env:
            - name: FLASK_APP
              value: "bmi_service.py"  # Set to your actual entry point file name
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: bmi-service
spec:
  selector:
    app: bmi-service
  ports:
    - protocol: TCP
      port: 5002
      targetPort: 5002
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: bmi-service-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: bmi-service
  minReplicas: 1
  maxReplicas: 5
