apiVersion: apps/v1
kind: Deployment
metadata:
  name: exercise-service
spec:
  replicas: 2  # Number of replicas (you can change this based on your requirements)
  selector:
    matchLabels:
      app: exercise-service
  template:
    metadata:
      labels:
        app: exercise-service
    spec:
      containers:
        - name: exercise-service
          image: abanikaurkohli/exercise_service_image:latest
          ports:
            - containerPort: 5003
          livenessProbe:
            httpGet:
              path: /health  # Health check path to match the Flask `/health` endpoint
              port: 5003
            initialDelaySeconds: 10  # Delay before starting to probe after container starts
            periodSeconds: 10  # How often to perform the probe
            failureThreshold: 3  # Number of failed probes before considering the container unhealthy
            successThreshold: 1  # Number of successful probes to consider the container healthy
          readinessProbe:
            httpGet:
              path: /readiness  # Readiness check path to match the Flask `/readiness` endpoint
              port: 5003
            initialDelaySeconds: 5  # Delay before starting to probe for readiness
            periodSeconds: 10  # How often to perform the probe
            failureThreshold: 3  # Number of failed probes before considering the container not ready
            successThreshold: 1  # Number of successful probes to consider the container ready
---
apiVersion: v1
kind: Service
metadata:
  name: exercise-service
spec:
  selector:
    app: exercise-service
  ports:
    - port: 5003
      targetPort: 5003
  type: NodePort
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: exercise-service-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: exercise-service
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
