apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: bmi-service
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: bmi-service
  minReplicas: 2
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80
